### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain' for AttachmentsController:Class Did you mean?  alias_method

### ISSUE THREAD

**Issue by minzak** [HugoHasenbein/redmine_more_code#1]
I have:
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
gem 3.0.3
Rails 5.2.4.1
And latest 4.1 redmine, but:

```
 bundle exec rake db:migrate RAILS_ENV=production 
rake aborted!
NoMethodError: undefined method `alias_method_chain' for AttachmentsController:Class
Did you mean?  alias_method
/opt/redmine/plugins/redmine_more_code/lib/redmine_more_code/patches/attachments_controller_patch.rb:31:in `block in included'
/opt/redmine/plugins/redmine_more_code/lib/redmine_more_code/patches/attachments_controller_patch.rb:28:in `class_eval'
/opt/redmine/plugins/redmine_more_code/lib/redmine_more_code/patches/attachments_controller_patch.rb:28:in `included'
/opt/redmine/plugins/redmine_more_code/lib/redmine_more_code/patches/attachments_controller_patch.rb:61:in `include'
/opt/redmine/plugins/redmine_more_code/lib/redmine_more_code/patches/attachments_controller_patch.rb:61:in `<top (required)>'
/opt/redmine/plugins/redmine_more_code/lib/redmine_more_code.rb:25:in `block in <top (required)>'
/opt/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```
This is solution, but i'm not ruby-ooder
https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

**Comment by Luckyvb** [comment]
#2

**Comment by Luckyvb** [comment]
To support old Rails:
```
          if Rails::VERSION::MAJOR >= 5
            alias_method :show_without_more_code, :show
            alias_method :show, :show_with_more_code
          else
            alias_method_chain :show, :more_code
          end
```

**Comment by etron770** [comment]
> To support old Rails:
> 
> ```
>           if Rails::VERSION::MAJOR >= 5
>             alias_method :show_without_more_code, :show
>             alias_method :show, :show_with_more_code
>           else
>             alias_method_chain :show, :more_code
>           end
> ```
I do not know where to place this code. 
I am lost ....

**Comment by etron770** [comment]
> To support old Rails:
> 
> ```
>           if Rails::VERSION::MAJOR >= 5
>             alias_method :show_without_more_code, :show
>             alias_method :show, :show_with_more_code
>           else
>             alias_method_chain :show, :more_code
>           end
> ```
I do not know where to place this code. 
I am lost ....

**Comment by HugoHasenbein** [comment]
Dear Knut,

the current version of redmine_more_code has already implemented the support of both Rails versions. Rail 5.0+ and Rails below 5.0.

If you do get errors, then there may either be a glitch / mixup in Rails or I have overseen a bug. Could you give me some more information, where redmine_more_code hangs?

Best regards

Stephan

**Comment by etron770** [comment]
Dear Stephan, thank you for your help.

```
Rails 5.2.4.2

ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

Debian Buster VM Server

```

Stucking during the update process from Redmine Version  3.4.3 to 4.1.1

At the first step Redmine was working exept entering the project page.

But I did an  gem install rails after that stage and now I am getting the ""We're sorry, but something went wrong." error at the web interface but the update process stucks at:

```
/opt/redmine# bundle exec rake db:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ActiveRecord::Associations::ClassMethods:Module
Did you mean?  alias_method
/opt/redmine/plugins/redmine_contacts/lib/redmine_contacts/patches/compatibility/active_record_base_patch.rb:28:in `block in included'
/opt/redmine/plugins/redmine_contacts/lib/redmine_contacts/patches/compatibility/active_record_base_patch.rb:27:in `class_eval'
/opt/redmine/plugins/redmine_contacts/lib/redmine_contacts/patches/compatibility/active_record_base_patch.rb:27:in `included'
/opt/redmine/plugins/redmine_contacts/lib/redmine_contacts/patches/compatibility/active_record_base_patch.rb:90:in `include'
/opt/redmine/plugins/redmine_contacts/lib/redmine_contacts/patches/compatibility/active_record_base_patch.rb:90:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/plugins/redmine_contacts/lib/redmine_contacts.rb:35:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/plugins/redmine_contacts/init.rb:115:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/lib/redmine/plugin.rb:181:in `block in load'
/opt/redmine/lib/redmine/plugin.rb:172:in `each'
/opt/redmine/lib/redmine/plugin.rb:172:in `load'
/opt/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/config/environment.rb:16:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)

```

**Comment by HugoHasenbein** [comment]
Dear Knut,

it seems the redmine_contacts plugin from redmine_up fails.

Do you have the commercial version of redmine_contacts? I have downloaded redmine_contacts free version and it seems the file is a bit different.

In any case, currently, it seems the culprit is not redmine_more_code...

best regards

Stephan

**Comment by etron770** [comment]
All plugins are free versions.
Trying to install the Plugins step by step, errors at:
redmine_checklists
redmine_contacts
redmine_finance
redmine_preview_inline
redmine_preview_office
redmine_preview_pdf
redmine_vote


working:
redmine_preview_office

so seven of eight are not working ....

**Comment by HugoHasenbein** [comment]
Dear Knut,

redmine_checklists, redmine_contacts and redmine_finance are from redmine up.

redmine_vote is from another author

redmine_preview_inline will soon be updated to work with redmine 4+
redmine_preview_office, redmine_preview_pdf will soon be integrated as one plugin working for redmine 4+

Please note, that Rails, the base of redmine has had a tremendous change in the way to patch functions. Thus, all plugins, that migrate from redmine 3+ to redmine 4+ need an internal upgrade, next to minor changes due to changes in the redmine code.

Soon, I will publish redmine_more_preview, which integrates

redmine_preview_office,
redmine_preview_pdf
redmine_preview_docx
redmine_more_code

best regards

Stephan

**Comment by etron770** [comment]
Dear Stephan,
I did software developing  lot of years . so I know the ammount work about bugfixing, new versions and so on.
And free open source plugins, mostly biuld in spartetime work. Thank's for that to all coder ...

But a general  question:

What about the previous data during the time until the plugins can be enabled.
Are they gone or will they appear again if the plugin will be enabled after the upgrades.

Ok not a problem with the preview plugins, but the plugins with additional data .


best regards 
Knut

**Comment by HugoHasenbein** [comment]
Dear Knut,

by your name I assume you speak German?

I can only talk for my plugins, I develop:

The preview plugins produce thumbnails or previews in a cache. There is no data in the database from these plugins. So you may just replace the plugins. Naturally, all previews will need to be created on the fly when using the new plugin.

For the other plugins, there is usually a migration path to carry data from redmine 3+ to redmine 4+.

So, no need to worry - you will probably not loose data

Best regards

Stephan
